### ISSUE TITLE
select a movie

### ISSUE THREAD

**Issue by Themadhood** [Themadhood/CSCI300-54_G9_Final_Project#11]
def Selection

randomly select a movie from bolth stacks
add bolth to self.stack_temp
determin if number is odd or even
take corisponding movie from self.stack_temp
return remaing movie to its lst
delete the selected movie from its lst
return selected movie

**Comment by mokorm2** [comment]
[CSCI300FinalProject.zip](https://github.com/Themadhood/CSCI300-54_G9_Final_Project/files/15046594/CSCI300FinalProject.zip)

Here you go!

**Comment by mokorm2** [comment]
Sorry this is the correct one 
[CSCI300FinalP.zip](https://github.com/Themadhood/CSCI300-54_G9_Final_Project/files/15046630/CSCI300FinalP.zip)

**Comment by Themadhood** [comment]
try python...........................

**Comment by mokorm2** [comment]
Ok. Heres the python version But i need help with something. My QT creater is not working for some reason when it comes to python so i had to use something else
[ForCSCI300FinalProject(In Python).zip](https://github.com/Themadhood/CSCI300-54_G9_Final_Project/files/15050762/ForCSCI300FinalProject.In.Python.zip)
